#!/usr/bin/env bash
# Read the /etc/passwd file line by line and extract the relevant information
while IFS=":" read -r username _ userid groupid homedir shell; do
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode x, more info about the user here: $username"
done < /etc/passwd
