#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code, and displays the data in a formatted list.

data=$(awk '{print $1, $9}' apache_access.log | sort | uniq -c | sort -nr)

echo "$data" | awk '{printf "%4d %s %s\n", $1, $2, $3}'
