#!/usr/bin/env bash
# 5-4_bad_luck_8_is_your_chance: Displays "Best School" 10 times, except for the 4th and 8th iterations

count=1
while [ $count -le 10 ]; do
    if [ $count -eq 4 ]; then
        echo "bad luck"
    elif [ $count -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    count=$((count + 1))
done
