#!/usr/bin/env bash
# Displays the content of the current directory in a list format, showing only the part of the name after the first dash

for file in *-*; do
    echo "file-$(basename "$file" | cut -d'-' -f2)"
done | sort
