#!/usr/bin/env bash
# This script lists the contents of the current directory, displaying only the part of the file name after the first dash

for file in *
do
    if [[ "$file" == *"-"* ]]
    then
        echo "file-$(basename "$file" | cut -d'-' -f2)"
    else
        echo "$file"
    fi
done | sort
