#!/usr/bin/env bash
# This Bash script manages a process called "manage_my_process"

PROCESS_NAME="manage_my_process"
PIDFILE="/var/run/${PROCESS_NAME}.pid"

case "$1" in
  start)
    echo "${PROCESS_NAME} started"
    touch "${PIDFILE}"
    ;;
  stop)
    echo "${PROCESS_NAME} stopped"
    rm -f "${PIDFILE}"
    ;;
  restart)
    echo "${PROCESS_NAME} restarted"
    ;;
  *)
    echo "Usage: ${PROCESS_NAME} {start|stop|restart}"
    exit 1
    ;;
esac
