#!/usr/bin/env bash
# This Bash script manages a process called "manage_my_process"

case "$1" in
  start)
    echo "manage_my_process started"
    touch /var/run/my_process.pid
    ;;
  stop)
    echo "manage_my_process stopped"
    rm -f /var/run/my_process.pid
    ;;
  restart)
    echo "manage_my_process restarted"
    ;;
  *)
    echo "Usage: manage_my_process {start|stop|restart}"
    exit 1
    ;;
esac
