#!/usr/bin/env bash
# This script displays the PID and process name of processes containing the word "bash"
# Get the list of process IDs containing the word "bash"

pids=$(pidof bash)
# Loop through the process IDs and display the PID and process name

for pid in $pids; do
    name=$(cat /proc/"$pid"/comm)
    echo "$pid $name"
done
